Process_list='com.tencent.mm.sandbox.updater.AppUpdaterUI
com.tencent.mm.sandbox.updater.AppInstallerUI
com.tencent.mm.plugin.appbrand.task.AppBrandTaskPreloadReceiver
com.tencent.mm.plugin.appbrand.task.AppBrandTaskPreloadReceiver1
com.tencent.mm.plugin.appbrand.task.AppBrandTaskPreloadReceiver2
com.tencent.mm.plugin.appbrand.task.AppBrandTaskPreloadReceiver3
com.tencent.mm.plugin.appbrand.task.AppBrandTaskPreloadReceiver4
com.tencent.mm.booter.MMReceivers$SandBoxProcessReceiver
com.tencent.mm.ipcinvoker.wx_extension.service.Appbrand0IPCService
com.tencent.mm.ipcinvoker.wx_extension.service.Appbrand1IPCService
com.tencent.mm.ipcinvoker.wx_extension.service.Appbrand2IPCService
com.tencent.mm.ipcinvoker.wx_extension.service.Appbrand3IPCService
com.tencent.mm.ipcinvoker.wx_extension.service.Appbrand4IPCService
com.tencent.mm.sandbox.monitor.ExceptionMonitorService
com.tencent.mm.service.ProcessService$SandBoxProcessService
com.tencent.mm.service.ProcessService$ToolsProcessService
com.tencent.mm.service.ProcessService$ToolsmpProcessService
com.tencent.smtt.sandbox.SandboxedProcessService0
com.tencent.smtt.sandbox.SandboxedProcessService1
com.tencent.mm.ipcinvoker.wx_extension.service.ToolsMpProcessIPCService
com.tencent.mm.ipcinvoker.wx_extension.service.ToolsProcessIPCService
com.tencent.mm.booter.MMReceivers$ToolsMpProcessReceiver
com.tencent.mm.booter.MMReceivers$ToolsProcessReceiver'
